apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policies
  namespace: default
data:
  policy.rego: |
    package istio.authz
    import future.keywords.if
    default allow = false
    allow if {
        input.attributes.request.http.headers["x-user"] == "admin"
    }
