apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: default
data:
  config.yaml: |
    decision_logs:
      console: true
    plugins:
      envoy_ext_authz_grpc:
        addr: ":9191"
        path: istio/authz/allow
        dry-run: false
        enable-reflection: false
